name: mad_pay
description: Mad Pay will help you make payments through Apple Pay and Google Pay
version: 2.1.3
repository: https://github.com/MadBrains/Mad-Pay-Flutter
issue_tracker: https://github.com/MadBrains/Mad-Pay-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  protobuf: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.madbrains.mad_pay
        pluginClass: MadPayPlugin
      ios:
        pluginClass: MadPayPlugin

